
---

- hosts: ansible

  tasks:
    - name: Make POST request
      ansible.builtin.uri:
        url: http://127.0.0.1:5000/
        method: GET
        body_format: json
      register: response

    - name: Print response
      debug:
        var: response