
---

- hosts: ansible

  tasks:

    - name: check URL status Grafana
      uri:
        url: http://<EXTERNAL-IP>:3000
    
    - name: check URL status Prometheus
      uri:
        url: http://<EXTERNAL-IP>:9090

    - name: check that a page returns successfully but fail if the down on targets page
      uri:
        url: 'http://<EXTERNAL-IP>:9090/targets?search='
        return_content: true
      register: prometheus